// examples/kitchen-sink/app/remote/examples/App.svelte
<script lang="ts">
  import type {Modal} from '../elements.ts';
  import type {RenderAPI} from '../../types.ts';

  export let api: RenderAPI;

  let count = 0;
  let modal: InstanceType<typeof Modal>;

  function handlePress() {
    count += 1;
  }

  function handleClose() {
    api.alert(`You clicked ${count} times!`);
    count = 0;
  }

  function handlePrimaryAction() {
    modal.close();
  }
</script>

<ui-stack spacing>
  <ui-text>
    Rendering example: <ui-text emphasis>{api.example}</ui-text>
  </ui-text>
  <ui-text>
    Rendering in sandbox: <ui-text emphasis>{api.sandbox}</ui-text>
  </ui-text>

  <ui-button>
    Open modal

    <ui-modal slot="modal" bind:this={modal} on:close={handleClose}>
      <ui-text>Click count: <ui-text emphasis>{count}</ui-text></ui-text>
      <ui-button on:press={handlePress}>Click me!</ui-button>
      <ui-button slot="primaryAction" on:press={handlePrimaryAction}>
        Close
      </ui-button>
    </ui-modal>
  </ui-button>
</ui-stack>

// examples/remote-ui/app/remote/app.tsx
/** @jsxRuntime automatic */
/** @jsxImportSource react */

import {useState} from 'react';
import {Button, Modal, Stack, Text} from './components';
import {RenderAPI} from '../types';

export function App({api}: {api: RenderAPI}) {
  return (
    <Stack spacing>
      <>
        <Text>
          Rendering example: <Text emphasis>remote-ui legacy</Text>
        </Text>
        <Button modal={<CountModal {...api} />}>Open modal</Button>
      </>
    </Stack>
  );
}

function CountModal({showAlert, closeModal}: RenderAPI) {
  const [count, setCount] = useState(0);

  const primaryAction = (
    <Button
      onPress={() => {
        closeModal();
      }}
    >
      Close
    </Button>
  );

  return (
    <Modal
      primaryAction={primaryAction}
      onClose={() => {
        if (count > 0) {
          showAlert(`You clicked ${count} times!`);
        }

        setCount(0);
      }}
    >
      <Stack spacing>
        <Text>
          Click count: <Text emphasis>{count}</Text>
        </Text>
        <Button
          onPress={() => {
            setCount((count) => count + 1);
          }}
        >
          Click me!
        </Button>
      </Stack>
    </Modal>
  );
}
